function [xyz_pts] = getAllProfilePoints(profile_struct)
    xyz_pts = [eval(['[',profile_struct.pointList.x.Text,']']), ...
               eval(['[',profile_struct.pointList.y.Text,']']), ...
               eval(['[',profile_struct.pointList.z.Text,']'])]';
end